---
driver:
  name: azurerm
  subscription_id: "<subscription-id>"
  location: 'North Europe'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.0.118

verifier:
  name: inspec

platforms:
  - name: centos-7.6
    driver:
      image_urn: OpenLogic:CentOS:7.6:7.6.20181219
      vm_name: centos-vm
    transport:
      ssh_key: ~/.ssh/azure

  - name: windows-server
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
      vm_tags: 
        ostype: windows
      data_disks:
        - lun: 0
          disk_size_gb: 40
    transport:
      name: winrm

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
